gemini_db_name: 'gemini_db/MVL_2018-01-12.gemini.db'
samtools_version: 'samtools/1.6'
vt_version: 'vt/0.577'
ref_genome: '/data/OGVFB/resources/mcgaughey_annotation_files/human_g1k_v37_decoy.fasta'
VEP_version: 'VEP/89'
vcfanno_version: 'vcfanno/0.2.9'
vcfanno_lua: '/home/$USER/git/casey_to_gemini/src/vcfanno_custom.lua'
vcfanno_conf: '/home/$USER/git/casey_to_gemini/src/vcfanno_exomes.conf'
vcf2db_version: 'vcf2db/2017.12.11'
gemini_version: 'gemini/0.20.1'
R_version: 'R/3.5.0'
pandoc_version: 'pandoc/2.1.1'
