gemini_db_name: 'gemini_db/MVL_2017-12-14.gemini.db'
samtools_version: 'samtools/1.6'
ref_genome: '/data/OGVFB/resources/human_g1k_v37_decoy.fasta'
VEP_version: 'VEP/89'
vcfanno_version: 'vcfanno/0.1.1'
vcfanno_lua: '/home/$USER/git/casey_to_gemini/src/vcfanno_custom.lua'
vcfanno_conf: '/home/$USER/git/casey_to_gemini/src/vcfanno_exomes.conf'
vcf2db_version: 'vcf2db/7dfc48a'
gemini_version: 'gemini/0.20.1'
R_version: 'R/3.4.0_gcc-6.2.0'
pandoc_version: 'pandoc/1.15.0.6'
